// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class jo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jo));
        
        string IMigrationMetadata.Id
        {
            get { return "201402211329579_jo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
